---
apiVersion: v1
kind: Secret
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
type: Opaque
data:
    keyfile: {{SECRET}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
  labels:
    name: {{SERVICE_NAME}}
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: {{SERVICE_NAME}}-mongod
    petset: {{SERVICE_NAME}}
---
apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  replicas: {{REPLICAS}}
  serviceName: {{SERVICE_NAME}}
  template:
    metadata:
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
        pod.alpha.kubernetes.io/init-containers: '[{"name":"install","image":"example.lijiaocn.com/lijiaob/mongo-init:{{VERSION}}","imagePullPolicy":"Always","env":[{"name":"DELETE_EXSITING_DATA","value":"{{DELETE_EXSITING_DATA}}"},{"name":"MONGODB_HIDDEN_USER","value":"{{MONGODB_HIDDEN_USER}}"},{"name":"MONGODB_HIDDEN_PWD","value":"{{MONGODB_HIDDEN_PWD}}"},{"name":"MONGODB_DEF_USER","value":"{{MONGODB_DEF_USER}}"},{"name":"MONGODB_DEF_PWD","value":"{{MONGODB_DEF_PWD}}"}],"volumeMounts":[{"name":"mongo-persistent-storage","mountPath":"/data/db"}]}]'
      labels:
        role: {{SERVICE_NAME}}-mongod
        petset: {{SERVICE_NAME}}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: mongo
          image: example.lijiaocn.com/lijiaob/mongo:{{VERSION}}
          command:
            - mongod
            - "--keyFile"
            - "/run/keyfile"
            - "--auth"
            - "--replSet"
            - rs0
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
            - name: keyfile
              mountPath: /run
              readOnly: false
        - name: mongo-sidecar
          image: example.lijiaocn.com/lijiaob/mongo-k8s-sidecar:{{VERSION}}
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "petset={{SERVICE_NAME}},role={{SERVICE_NAME}}-mongod"
            - name: KUBERNETES_MONGO_SERVICE_NAME
              value: "{{SERVICE_NAME}}"
            - name: KUBE_NAMESPACE
              value: "{{NAMESPACE}}"
            - name: KUBERNETES_CLUSTER_DOMAIN
              value: "{{CLUSTER_DOMAIN}}"
            - name: MONGODB_USERNAME
              value: "{{MONGODB_HIDDEN_USER}}"
            - name: MONGODB_PASSWORD
              value: "{{MONGODB_HIDDEN_PWD}}"
            - name: MONGODB_DATABASE
              value: "admin"
      volumes:
        - name: keyfile
          secret:
             secretName: {{SERVICE_NAME}}
             defaultMode: 256
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{CAPACITY}}
